insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5850, 'Nkaus Airport', 'Nkaus', 65);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6336, 'Opuwa Airport', 'Opuwa', 39);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5034, 'Bay City Municipal Airport', 'Bay City', 70);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3007, 'Anaktuvuk Pass Airport', 'Anaktuvuk Pass', 5);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4188, 'St Paul Island Airport', 'St Paul Island', 73);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7535, 'Teruel Airport', 'Teruel', 74);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9842, 'Yenkis(Yankisa) Airport', null, 79);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6770, 'Bizant Airport', 'Lakefield National Park', 12);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (8590, 'Scusciuban Airport', 'Scusciuban', 13);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6848, 'Pinehouse Lake Airport', 'Pinehouse Lake', 7);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6725, 'Vatukoula Airport', 'Vatukoula', 26);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1610, 'Hobart International Airport', 'Hobart', 23);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1615, 'Rokot Airport', 'Rokot-Sumatra Island', 5);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9150, 'Garden Point Airport', null, 61);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6962, 'Orangeburg Municipal Airport', 'Orangeburg', 27);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1034, 'Bratsk Airport', 'Bratsk', 32);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5559, 'Bingöl Çeltiksuyu Airport', 'Bingöl', 83);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6564, 'Peter O Knight Airport', 'Tampa', 4);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1882, 'Sitkinak Airport', 'Sitkinak Island', 95);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9156, 'Hualien Airport', 'Hualien City', 36);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9030, 'Nnamdi Azikiwe International Airport', 'Abuja', 12);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2559, 'Lese Airport', 'Lese', 90);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5283, 'Niigata Airport', 'Niigata', 19);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1005, 'Tucumcari Municipal Airport', 'Tucumcari', 88);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7350, 'Thunder Bay Airport', 'Thunder Bay', 38);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5780, 'Utti Air Base', 'Utti / Valkeala', 37);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6495, 'Yakutsk Airport', 'Yakutsk', 22);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6759, 'Hale County Airport', 'Plainview', 6);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6242, 'Mount Gordon Airport', 'Mount Gordon Mine', 48);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4444, 'Santa Izabel do Morro Airport', 'Cristalândia', 3);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4227, 'Jodhpur Airport', 'Jodhpur', 58);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3662, 'Nanaimo Harbour Water Airport', 'Nanaimo', 26);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3831, 'Shillong Airport', 'Shillong', 99);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9559, 'Eduardo Falla Solano Airport', 'San Vicente Del Caguán', 46);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (8958, 'Porto Santo Airport', 'Vila Baleira', 64);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1251, 'Winston Field', 'Snyder', 82);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (8740, 'Melbourne Moorabbin Airport', 'Melbourne', 8);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4785, 'Kraków John Paul II International Airport', 'Kraków', 71);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3840, 'Long Lellang Airport', 'Long Datih', 63);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9219, 'False Pass Airport', 'False Pass', 93);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1248, 'Socotra International Airport', 'Socotra Islands', 94);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5768, 'Fazenda São Francisco Airport', 'Magda', 43);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3899, 'Berkley Municipal Heliport', 'Oakland', 14);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4044, 'Sultan Mahmud Badaruddin II Airport', 'Palembang-Sumatra Island', 68);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3191, 'Rupsi India Airport', null, 51);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2131, 'Gardo Airport', 'Gardo', 81);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3856, 'Bagan Airport', 'Nyaung U', 49);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7641, 'Bryce Canyon Airport', 'Bryce Canyon', 83);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1504, 'Tunis Carthage International Airport', 'Tunis', 47);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3571, 'Jomo Kenyatta International Airport', 'Nairobi', 94);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1939, 'Rundu Airport', 'Rundu', 83);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9541, 'Khabarovsk-Novy Airport', 'Khabarovsk', 39);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9718, 'Vejrø', null, 65);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6539, 'Mococa Airport', 'Mococa', 26);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4522, 'Beni Airport', 'Beni', 97);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5083, 'Santa Fe Municipal Airport', 'Santa Fe', 64);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6835, 'Jenpeg Airport', 'Jenpeg', 45);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1691, 'Humberside Airport', 'Grimsby', 32);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (8837, 'Estherville Municipal Airport', 'Estherville', 29);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7801, 'El Obeid Airport', 'Al-Ubayyid', 18);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4186, 'Bachigualato Federal International Airport', 'Culiacán', 81);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7563, 'Guajará-Mirim Airport', 'Guajará-Mirim', 26);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2357, 'Chicago Executive Airport', 'Chicago/Prospect Heights/Wheeling', 15);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (9474, 'Victoria River Downs Airport', null, 100);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4154, 'DuBois Regional Airport', 'Dubois', 31);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7494, 'Provincetown Municipal Airport', 'Provincetown', 64);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1823, 'Alliance Municipal Airport', 'Alliance', 33);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4752, 'Gap - Tallard Airfield', null, 20);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2584, 'Mesquite Airport', 'Mesquite', 28);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3595, 'Semera Airport', 'Semera', 35);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6129, 'Corisco International Airport', 'Corisco Island', 32);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2352, 'Dirranbandi Airport', null, 2);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5317, 'Pukatawagan Airport', 'Pukatawagan', 70);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3324, 'Exmouth Airport', null, 21);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2172, 'Blue Lagoon Seaplane Base', 'Nanuya Lailai Island', 85);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5514, 'Qiqihar Sanjiazi Airport', 'Qiqihar', 47);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7290, 'Tan Tan Airport', 'Tan Tan', 61);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6812, 'Andi Jemma Airport', 'Masamba-Celebes Island', 64);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4754, 'Gandajika Airport', 'Gandajika', 99);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4778, 'Rinkenberger Restricted Landing Area', 'Bradford', 82);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1213, 'De La Independencia Airport', 'Rancagua', 58);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3055, 'A L Mangham Jr. Regional Airport', 'Nacogdoches', 21);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4347, 'Gulu Airport', 'Gulu', 1);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (2450, 'Cessnock Airport', null, 62);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4293, 'Lester B. Pearson International Airport', 'Toronto', 39);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3966, 'Dadu West Airport', 'Dadu', 84);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (8542, 'Floyd Bennett Memorial Airport', 'Glens Falls', 7);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (7190, 'Basango Mboliasa Airport', 'Kiri', 20);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1948, 'Pau Pyrénées Airport', 'Pau/Pyrénées (Uzein)', 100);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4857, 'Rupsi India Airport', null, 52);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4389, 'Cue Airport', null, 70);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4745, 'Las Breas Airport', 'Taltal', 26);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (1362, 'Coronel Enrique Soto Cano Air Base', 'Comayagua', 2);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6659, 'Cadete FAP Guillermo Del Castillo Paredes Airport', 'Tarapoto', 27);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6301, 'West Woodward Airport', 'Woodward', 63);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (4391, 'Erigavo Airport', 'Erigavo', 42);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (6555, 'Erfurt Airport', 'Erfurt', 40);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (8836, 'Bethel Seaplane Base', 'Bethel', 18);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (5109, 'Luderitz Airport', 'Luderitz', 73);
insert into Klice (Cislo, NazevMistnosti, OznaceniDveri, PocetKusu) values (3116, 'Amsterdam Airport Schiphol', 'Amsterdam', 25);
