insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Anglesey Airport', 'Angelsey', 51);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Ken Jones Airport', 'Ken Jones', 13);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Lengbati Airport', null, 34);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Lydd Airport', 'Lydd, Ashford', 78);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('General Mitchell International Airport', 'Milwaukee', 87);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Fond du Lac County Airport', 'Fond du Lac', 11);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Amchitka Army Airfield', 'Amchitka Island', 62);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Arutua Airport', null, 33);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Eastern Sierra Regional Airport', 'Bishop', 80);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Capitan Fuentes Martinez Airport Airport', 'Porvenir', 41);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('J F Mitchell Airport', 'Bequia', 48);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Montpellier-Méditerranée Airport', 'Montpellier/Méditerranée', 53);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Maygatka Airport.', 'Sovetskaya Gavan', 77);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Brunswick Golden Isles Airport', 'Brunswick', 97);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Hartley Bay Seaplane Base', 'Hartley Bay', 31);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Prince Mohammad Bin Abdulaziz Airport', 'Medina', 26);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Fallon Municipal Airport', 'Fallon', 100);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Beverley Springs Airport', null, 88);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Benson Municipal Airport', 'Benson', 20);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Pitts Town Airport', 'Pitts Town', 23);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Selfridge Air National Guard Base Airport', 'Mount Clemens', 97);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Grant County Airport', 'Silver City', 47);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Monroe County Aeroplex Airport', 'Monroeville', 51);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Vancouver International Airport', 'Vancouver', 3);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Freeman Municipal Airport', 'Seymour', 10);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Villa Dolores Airport', 'Villa Dolores', 56);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Schleswig Air Base', 'Jagel', 85);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Santa Teresita Airport', 'Santa Teresita', 99);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Basco Airport', 'Basco', 80);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Lonely Air Station', 'Lonely', 81);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Unst Airport', 'Shetland Islands', 36);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Jurado Airport', 'Jurado', 9);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Ralph C Weiser Field', 'Magnolia', 42);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Cudal Airport', null, 94);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Phoenix Deer Valley Airport', 'Phoenix', 56);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Erie International Tom Ridge Field', 'Erie', 71);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Voinjama Airport', 'Voinjama', 66);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('David Wayne Hooks Memorial Airport', 'Houston', 35);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Lumi Airport', 'Lumi', 15);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Mysore Airport', 'Mysore', 9);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Hartley Bay Seaplane Base', 'Hartley Bay', 39);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Stara Zagora Airport', 'Stara Zagora', 98);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Oktyabrskiy Airport', 'Kzyl-Yar', 51);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Pincher Creek Airport', 'Pincher Creek', 83);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Cliff Hatfield Memorial Airport', 'Calipatria', 12);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Cambridge Dorchester Airport', 'Cambridge', 63);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Inyati Airport', 'Inyati', 31);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Neuchatel Airport', null, 59);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Kemi-Tornio Airport', 'Kemi / Tornio', 1);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Ben Bruce Memorial Airpark', 'Evadale', 17);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Kastamonu Airport', 'Kastamonu', 48);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Bay City Municipal Airport', 'Bay City', 32);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Fairbanks International Airport', 'Fairbanks', 44);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Senai International Airport', 'Johor Bahru', 75);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Stung Treng Airport', 'Stung Treng', 49);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Launceston Airport', 'Launceston', 23);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Guerrero Negro Airport', 'Guerrero Negro', 61);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Marechal Cunha Machado International Airport', 'São Luís', 95);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Jicalapa Airport', 'Jicalapa', 52);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Eureka Airport', 'Eureka', 44);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Belaya Gora Airport', 'Belaya Gora', 17);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Port Moresby Jacksons International Airport', 'Port Moresby', 73);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Copenhagen Kastrup Airport', 'Copenhagen', 82);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Ocean Falls Seaplane Base', 'Ocean Falls', 27);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Bagani Airport', 'Bagani', 46);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Sary-Arka Airport', 'Karaganda', 1);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Reykjahlíð Airport', 'Myvatn', 73);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Alfredo Vásquez Cobo International Airport', 'Leticia', 5);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Taylor Airport', 'Taylor', 59);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Fakahina Airport', 'Fakahina', 75);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Tosontsengel Airport', 'Tosontsengel', 26);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Imonda Airport', 'Imonda', 59);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Lokpriya Gopinath Bordoloi International Airport', 'Guwahati', 44);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Bragado Airport', 'Bragado', 58);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Yalumet Airport', 'Yalumet', 61);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Mushaf Air Base', 'Sargodha', 90);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Letterkenny Airport', 'Letterkenny', 34);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Malekolon Airport', 'Babase Island', 97);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Nekemte Airport', 'Nekemte', 9);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Zemio Airport', 'Zemio', 8);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('General WM J Fox Airfield', 'Lancaster', 40);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Mubatuba Airport', 'Mubatuba', 74);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Nanping Wuyishan Airport', 'Wuyishan', 38);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Kaolack Airport', 'Kaolack', 21);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Sultan Mahmud Airport', 'Kuala Terengganu', 41);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Douglas-Charles Airport', 'Marigot', 87);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Ambunti Airport', 'Ambunti', 18);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Fuyang Xiguan Airport', 'Fuyang', 70);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Barimunya Airport', null, 8);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Tambolaka Airport', 'Waikabubak-Sumba Island', 21);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Louisville International Standiford Field', 'Louisville', 75);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Beech Factory Airport', 'Wichita', 11);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Colon Airport', 'Marcala', 10);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('London Luton Airport', 'London', 87);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Bahja Airport', 'Bahja', 45);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('N''Kolo-Fuma Airport', 'N''Kolo-Fuma', 96);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Mont Joli Airport', 'Mont-Joli', 62);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Ampanihy Airport', 'Ampanihy', 8);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('Tokoroa Airfield', 'Tokoroa', 28);
insert into Klice (NazevMistnosti, OznaceniDveri, PocetKusu) values ('San Antonio Copalar Airport', 'Comitán', 81);
